/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.Frame;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
/**
 *
 * @author JAY
 */
public class DeleteFile extends javax.swing.JFrame {

    /**
     * Creates new form DeleteFile
     */
    public DeleteFile() {
        initComponents();
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        qttpanel = new javax.swing.JPanel();
        qtt = new javax.swing.JLabel();
        ticketid = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        back = new javax.swing.JButton();
        qtt1 = new javax.swing.JLabel();
        titlebgpanel = new javax.swing.JPanel();
        title1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        qttpanel.setBackground(new java.awt.Color(51, 51, 51));
        qttpanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        qtt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        qtt.setForeground(new java.awt.Color(255, 255, 255));
        qtt.setText("Ticket Cancellation");

        ticketid.setBackground(new java.awt.Color(51, 51, 51));
        ticketid.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ticketid.setForeground(new java.awt.Color(255, 255, 255));
        ticketid.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 102, 0)));

        submit.setBackground(new java.awt.Color(255, 153, 0));
        submit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        submit.setForeground(new java.awt.Color(255, 255, 255));
        submit.setText("Submit");
        submit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        submit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        back.setBackground(new java.awt.Color(255, 153, 0));
        back.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("Back");
        back.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        qtt1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        qtt1.setForeground(new java.awt.Color(255, 255, 255));
        qtt1.setText(" Enter Ticket ID  :");

        javax.swing.GroupLayout qttpanelLayout = new javax.swing.GroupLayout(qttpanel);
        qttpanel.setLayout(qttpanelLayout);
        qttpanelLayout.setHorizontalGroup(
            qttpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(qttpanelLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(qttpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ticketid, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, qttpanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(qttpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, qttpanelLayout.createSequentialGroup()
                        .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, qttpanelLayout.createSequentialGroup()
                        .addComponent(qtt, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(qttpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, qttpanelLayout.createSequentialGroup()
                    .addContainerGap(87, Short.MAX_VALUE)
                    .addComponent(qtt1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(71, 71, 71)))
        );
        qttpanelLayout.setVerticalGroup(
            qttpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(qttpanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(qtt, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102)
                .addComponent(ticketid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(qttpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(qttpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(qttpanelLayout.createSequentialGroup()
                    .addGap(118, 118, 118)
                    .addComponent(qtt1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(273, Short.MAX_VALUE)))
        );

        titlebgpanel.setBackground(new java.awt.Color(255, 153, 0));

        title1.setBackground(new java.awt.Color(255, 255, 255));
        title1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        title1.setForeground(new java.awt.Color(255, 255, 255));
        title1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title1.setText("भारतीय रेल");

        javax.swing.GroupLayout titlebgpanelLayout = new javax.swing.GroupLayout(titlebgpanel);
        titlebgpanel.setLayout(titlebgpanelLayout);
        titlebgpanelLayout.setHorizontalGroup(
            titlebgpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlebgpanelLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(title1, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
                .addGap(72, 72, 72))
        );
        titlebgpanelLayout.setVerticalGroup(
            titlebgpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titlebgpanelLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(title1, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titlebgpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(qttpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(titlebgpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qttpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        HomeFrame homeFrame = null;
    for (Frame frame : Frame.getFrames()) {
        if (frame instanceof HomeFrame) {
            homeFrame = (HomeFrame) frame;
            break;
        }
    }

    // If HomeFrame exists, make it visible and dispose of the current BookFile frame
    if (homeFrame != null) {
        homeFrame.setVisible(true);
        this.dispose();  // Dispose of the current BookFile frame
    } else {
        homeFrame = new HomeFrame();
        homeFrame.setVisible(true);
        this.dispose();  // Dispose of the current BookFile frame
    }
    }//GEN-LAST:event_backActionPerformed
     private void submitActionPerformed(java.awt.event.ActionEvent evt) {
        // Get the ticket ID from the text field
        String ticketIDText = ticketid.getText();

        // Check if the ticket ID is provided
        if (ticketIDText.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter a Ticket ID.");
            return;
        }

        // Parse the ticket ID to an integer
        int ticketID = Integer.parseInt(ticketIDText);

        try {
            // Establish connection to the database
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/train", "root", "vaishnavi");

            // Prepare the DELETE query
            String deleteQuery = "DELETE FROM ticket WHERE id = ?";

            // Create the PreparedStatement
            PreparedStatement pstmt = con.prepareStatement(deleteQuery);

            // Set the ticket ID parameter
            pstmt.setInt(1, ticketID);

            // Execute the DELETE query
            int rowsAffected = pstmt.executeUpdate();

            if (rowsAffected > 0) {
                // Inform the user about successful deletion
                javax.swing.JOptionPane.showMessageDialog(this, "Ticket ID " + ticketID + " deleted successfully.");
            } else {
                // Inform the user if no rows were deleted
                javax.swing.JOptionPane.showMessageDialog(this, "Ticket ID " + ticketID + " not found.");
            }

            // Close the PreparedStatement and connection
            pstmt.close();
            con.close();
            HomeFrame homeFrame = new HomeFrame();
            homeFrame.setVisible(true);
            this.dispose();

        } catch (SQLException e) {
            // Handle any SQL errors
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "An error occurred while deleting the ticket.");
        } catch (NumberFormatException e) {
            // Handle the case where ticketIDText is not a valid integer
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter a valid Ticket ID.");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteFile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteFile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel qtt;
    private javax.swing.JLabel qtt1;
    private javax.swing.JPanel qttpanel;
    private javax.swing.JButton submit;
    private javax.swing.JTextField ticketid;
    private javax.swing.JLabel title1;
    private javax.swing.JPanel titlebgpanel;
    // End of variables declaration//GEN-END:variables
}
